# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new Beta Build to Internal"
    lane :deploy do
      upload_to_play_store(
        track: 'internal',
        release_status: 'draft',
        ipa: '../build/ios/ipa/*.ipa'
#         aab: '/Users/Herman/Downloads/Zap/zapX/build/app/outputs/bundle/release/app-release.aab'
      )
    end

    lane :release do
      # api_key = app_store_connect_api_key(
      #   key_id: "C4T5FR95XK",
      #   issuer_id: "69a6de7b-22eb-47e3-e053-5b8c7c11a4d1",
      #   key_filepath: "fastlane/AuthKey_C4T5FR95XK.p8",
      #   duration: 1200, # optional (maximum 1200)
      #   in_house: false # optional but may be required if using match/sigh
      # )

      upload_to_testflight(
        apple_id: "6446452082",
       # api_key: api_key,
        skip_submission: true,
        ipa: "../build/ios/ipa/zap.ipa",
        skip_waiting_for_build_processing: true,
      )
    end
end
